version: '3.3'
services:
  hrapi:
    image: hrapi:latest
    restart: always
    ports:
      - "8080:8080"
  hrclient:
    image: hrclient:latest
    ports:
      - "4200:80"
    environment:
      - NGINX_PORT=80
    restart: always

